In [248]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
%matplotlib inline 
import seaborn as sns

[Data Description](https://towardsdatascience.com/things-you-didnt-know-about-the-boston-housing-dataset-2e87a6f960e8#:~:text=Each%20of%20the%20506%20rows,and%20per%20capita%20crime%20rate.)

In [249]:
df = pd.read_csv('C:\\Users\\harip\\Desktop\\Datascience\\data\\BostonHousing.csv')
df.shape

(506, 14)

In [250]:
df.head(3)
df.rename({'medv' : 'price'},axis=1,inplace=True)

In [251]:
round(df.describe(),1)

crim     zn  indus   chas    nox     rm    age    dis    rad    tax  \
count  506.0  506.0  506.0  506.0  506.0  506.0  506.0  506.0  506.0  506.0   
mean     3.6   11.4   11.1    0.1    0.6    6.3   68.6    3.8    9.5  408.2   
std      8.6   23.3    6.9    0.3    0.1    0.7   28.1    2.1    8.7  168.5   
min      0.0    0.0    0.5    0.0    0.4    3.6    2.9    1.1    1.0  187.0   
25%      0.1    0.0    5.2    0.0    0.4    5.9   45.0    2.1    4.0  279.0   
50%      0.3    0.0    9.7    0.0    0.5    6.2   77.5    3.2    5.0  330.0   
75%      3.7   12.5   18.1    0.0    0.6    6.6   94.1    5.2   24.0  666.0   
max     89.0  100.0   27.7    1.0    0.9    8.8  100.0   12.1   24.0  711.0   

       ptratio      b  lstat  price  
count    506.0  506.0  506.0  506.0  
mean      18.5  356.7   12.7   22.5  
std        2.2   91.3    7.1    9.2  
min       12.6    0.3    1.7    5.0  
25%       17.4  375.4    7.0   17.0  
50%       19.0  391.4   11.4   21.2  
75%       20.2  396.2   17.0   25.0  
max       22.0  396.9   38.0   50.0

In [252]:
# DIVIDING THE DATA FOR TRAIN - TEST SPLIT, Independent and Dependenet Value
    # X - Dataframe 
X = df.iloc[:,:-1] # Independent features
    # y - Array ,List
y = df.iloc[:,-1] # Dependent features

In [253]:
X.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  
0  396.90   4.98  
1  396.90   9.14  
2  392.83   4.03  
3  394.63   2.94  
4  396.90   5.33

In [254]:
y.head()

0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
Name: price, dtype: float64

You get multiple Hyperparameter Tuning in L1 and L2 regularization

LINEAR_REGRESSION : NOT USING GENERIC Train_Test_Split, Using - Quick Reference

BEST PRACTICE IS TO USE TRAIN TEST SPLIT

In [255]:
from sklearn.model_selection import cross_val_score# impt
from sklearn.linear_model import LinearRegression # module
from sklearn.preprocessing import StandardScaler
lr = LinearRegression() # model

In [256]:
from sklearn.model_selection import train_test_split as tts

In [257]:
X_train,X_test,y_train,y_test = tts(X,y,test_size=0.3,random_state=69)

In [258]:
print(f"X_train : {X_train.shape}, y_train : {y_train.shape}")

X_train : (354, 13), y_train : (354,)


In [259]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [260]:
lr.fit(X_train,y_train)

LinearRegression()

In [261]:
lr.predict(X_test)

array([28.43052286, 33.39815874, 19.27818382, 29.29441056, 29.73865417,
       14.83937777, 18.89257636, 20.96965758, 12.15061237, 24.60231963,
       20.45001084, 23.84057159, 19.42878389, 21.47543934, 16.83148912,
       22.6016457 , 20.20243108, 35.98748787, 28.99266974, 21.90855279,
       17.98802407, 23.59496919, 21.97732166, 28.38645386, 20.68485982,
       35.2983874 , 16.11638974, 15.30536295, 16.01743418, 29.8769224 ,
       -6.44995239, 27.78237952, 12.24844651, 28.23719918, 24.89668063,
       28.49592522, 13.09846082, 13.69178273, 24.29870528, 27.05328768,
       15.92507797, 16.14558867, 25.62669696, 18.26387639,  2.77222794,
       30.23147098, 26.29319659, 20.27627639, 23.37115948, 23.71653404,
       18.20774992, 30.7826089 , 26.8817391 , 22.10925317, 13.99846704,
       30.48732406, 26.46959508,  3.27579648, 25.04825753, 29.55046657,
       32.87273468, 21.92706798, 13.02016561, 32.92027104, 24.2638522 ,
       25.95655619, 24.3825474 , 22.78610583, 20.32880383, 35.70

In [262]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test,lr.predict(X_test))
mse

24.326154952243574

In [263]:
cvs = cross_val_score(lr,X_train,y_train,scoring='neg_mean_squared_error',cv=5) # Error all 5 CV
cvs

array([-22.99163857, -27.60848858, -22.07511321, -29.07875002,
       -17.79236413])

In [264]:
print(abs(np.mean(cvs)))

23.909270899891084


This is using the Cross-val-score

In [265]:
cvs = cross_val_score(lr,X,y,scoring='neg_mean_squared_error',cv=5) # Error all 5 CV
cvs

array([-12.46030057, -26.04862111, -33.07413798, -80.76237112,
       -33.31360656])

In [266]:
# for i in range(2,10):
#     cvs = cross_val_score(lr,X,y,scoring='neg_mean_squared_error',cv=i) # Error all 5 CV
#     print(cvs)

[Why Cross_Val_Score](https://youtu.be/TelJFE7bx0Q?t=1380)

In [267]:
# Lets find the average accuracy of all the 5
#print(abs(np.mean(cvs)))
print(np.mean(cvs))

-37.13180746769901


If you want to predict train_test_split

To Over-come the over fitting we will use Ridge and Lasso

In [268]:
# here we use two diff libraries
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV # help with hyper-parameter tuning

In [269]:
# alpha hyper-parameter, max_iter hyper-parameter
r = Ridge()
params= {'alpha' : [1e-15,1e-10,1e-8,1e-2,1,5,10,20]} # combination of alpha is taken and where every the model performs well that is returned , you can keeeeepppppp anyyyyyy value 
params2= {'alpha' : [1e-15,1e-10,1e-8,1e-2,1,5,10,20,30,25,40,45,50,55,60,65,100]} # combination of alpha is taken and where every the model performs well that is returned , you can keeeeepppppp anyyyyyy value 
cv = GridSearchCV(r,params,scoring='neg_mean_squared_error',cv = 5) # same as cross-val
cv = GridSearchCV(r,params2,scoring='neg_mean_squared_error',cv = 5) # same as cross-val
# model and parameters
# what ever best params you get apply on this 
# here you can pass x_train and y_train
cv.fit(X,y)

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': [1e-15, 1e-10, 1e-08, 0.01, 1, 5, 10, 20, 30,
                                   25, 40, 45, 50, 55, 60, 65, 100]},
             scoring='neg_mean_squared_error')

In [270]:
print(cv.best_params_)
print(cv.best_score_)
# if -ve value increases then ridge regression is not fit 
# if you scale it will give much more better-performance

{'alpha': 100}
-29.905701947540358


In [271]:
# now when we compare to the above mse we got it has reduced from -37 to -32, but -32 is close to 0 , so ridge is not useful , so lets try with lasso

Instead of performing all the above steps we can use RidgeCV

from sklearn.linear_model import Lasso

In [272]:
from sklearn.linear_model import Lasso
l = Lasso()
params= {'alpha' : [1e-15,1e-10,1e-8,1e-2,1,5,10,20]} # combination of alpha is taken and where every the model performs well that is returned , you can keeeeepppppp anyyyyyy value 
params2= {'alpha' : [1e-15,1e-10,1e-8,1e-2,1,5,10,20,30,25,40,45,50,55,60,65,100]}
cv = GridSearchCV(l,params2,scoring='neg_mean_squared_error',cv = 15) # same as cross-val
# model and parameters
# what ever best params you get apply on this 
# here you can pass x_train and y_train
cv.fit(X,y)

c:\Users\harip\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.117e+03, tolerance: 4.120e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\harip\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.708e+03, tolerance: 4.175e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\harip\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.164e+03, toleranc

GridSearchCV(cv=15, estimator=Lasso(),
             param_grid={'alpha': [1e-15, 1e-10, 1e-08, 0.01, 1, 5, 10, 20, 30,
                                   25, 40, 45, 50, 55, 60, 65, 100]},
             scoring='neg_mean_squared_error')

In [273]:
print(cv.best_params_)
print(cv.best_score_)

{'alpha': 0.01}
-32.176596258579345


In [274]:
df.head(2)

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   

       b  lstat  price  
0  396.9   4.98   24.0  
1  396.9   9.14   21.6

In [275]:
# now lets take train and test split
X = df.iloc[:,:-1]
y = df.iloc[:,-1]
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
from sklearn.model_selection import train_test_split as tts
X_train,X_test,y_train,y_test = tts(X,y,test_size=0.3,random_state=69)
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [276]:
from sklearn.linear_model import Ridge,Lasso
from sklearn.model_selection import GridSearchCV
r = Ridge()
l=Lasso()
params = {'alpha' : [1e-10,1e-20,1e-5,1e-10,1,5,15,20,25,30,35,40,45,50,60,65,85,100]}
gsr = GridSearchCV(r,params,scoring='neg_mean_squared_error',cv = 10)
gsl = GridSearchCV(l,params,scoring='neg_mean_squared_error',cv = 10)
# do we have to fit our model
gsr.fit(X_train,y_train)
gsl.fit(X_train,y_train)

c:\Users\harip\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.359e+03, tolerance: 2.650e+00 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
c:\Users\harip\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.391e+03, tolerance: 2.730e+00 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linea

GridSearchCV(cv=10, estimator=Lasso(),
             param_grid={'alpha': [1e-10, 1e-20, 1e-05, 1e-10, 1, 5, 15, 20, 25,
                                   30, 35, 40, 45, 50, 60, 65, 85, 100]},
             scoring='neg_mean_squared_error')

In [277]:
print(gsr.best_params_) # best parameter
print(gsr.best_score_) # error

{'alpha': 5}
-23.448014585394667


In [278]:
print(gsl.best_params_) # best parameter
print(gsl.best_score_) # error

{'alpha': 1e-05}
-23.49071823296078


In [279]:
gsr.predict(X_test)

array([28.46852618, 33.13004677, 19.23354696, 29.28300565, 29.92243723,
       15.16158908, 19.03386446, 20.87504293, 12.89820441, 24.63571388,
       20.66540354, 24.32257742, 19.44312713, 21.71529784, 17.0502009 ,
       22.64916756, 20.01174486, 35.88248588, 28.85399137, 21.91717097,
       18.17570215, 23.54993502, 22.63235363, 28.29288833, 20.18453935,
       34.90654017, 16.32980838, 15.54115231, 16.24391031, 29.63430929,
       -6.06416508, 27.94769382, 12.44841969, 28.15842898, 25.06980422,
       28.63133016, 13.35114305, 13.96989459, 24.00611934, 27.19992887,
       16.08292795, 16.19614946, 25.69859748, 18.18227838,  2.77933882,
       30.0172731 , 26.11005822, 20.88419254, 23.41436083, 23.8187238 ,
       18.18097648, 30.87281168, 26.77036355, 22.23018678, 14.21853738,
       30.53734455, 26.54620076,  3.89571404, 25.14801411, 29.26946449,
       32.75053006, 21.64796738, 13.20248318, 33.11071026, 24.30774734,
       26.13079076, 24.17860426, 22.74376344, 20.15258044, 35.57

In [280]:
al = gsl.predict(X_test)
ar = gsr.predict(X_test)

In [285]:
from sklearn.metrics import r2_score as r2
# adj = (1-(1-r2)*(len(df.shape[1])-1) / (df.shape[1]-1-1))
# adj

In [282]:
lscrore = r2(y_test,al)
ar_scrore = r2(y_test,ar)
lscrore

0.6927437301106849

In [283]:
ar_scrore

0.6966588975186333

In [ ]:
# https://www.youtube.com/watch?v=TelJFE7bx0Q&t=1622s